# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: Traffy -- A traffic simulator in Pygame

theme:
  name: material

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js
